### ISSUE TITLE
Quelques retours sur votre code

### ISSUE THREAD

**Issue by nivetml** [gmed2b/ateliers-prog#1]
- Pourquoi des clés poids sous la forme de chaines de caractères ? Pourquoi ne pas avoir simplement mis des entiers ? Surtout qu'après vous les retransformez en entier...
https://github.com/gmed2b/ateliers-prog/blob/f8d2c35f05aeff509b8623c3fc1d19720adf37b9/atelier0/affranchissement.py#L16C12-L16C14
- Et si num égal 3 ou 25 ?
https://github.com/gmed2b/ateliers-prog/blob/124df0d26b9e6b99fbd20d41ea0269c9771bdf44/atelier1/equation.py#L17C17-L17C17
- Précisez dans la docstring que le a doit être différent de zéro... Autrement rien n'empêche d'appeler votre fonction avec a=0 et cela fera planter votre programme ! Pourquoi avoir traité ce cas dans la fonction du dessus et pas dans celle là ?
https://github.com/gmed2b/ateliers-prog/blob/124df0d26b9e6b99fbd20d41ea0269c9771bdf44/atelier1/equation.py#L16

**Comment by gmed2b** [comment]
`Pourquoi des clés poids sous la forme de chaines de caractères ? Pourquoi ne pas avoir simplement mis des entiers ? Surtout qu'après vous les retransformez en entier...`
- Erreur d'inattention de ma part. Simple habitude d'écrire des JSON, je ne pensais que c'était possible en Python.

`Et si num égal 3 ou 25 ?`
- Le paramètre num peut avoir les valeurs 1 ou 2 uniquement. C'est inclue dans la logique de l'algorithme et ce n'est pas une valeur atteignable par l'utilisateur.

`Précisez dans la docstring que le a doit être différent de zéro... Autrement rien n'empêche d'appeler votre fonction avec a=0 et cela fera planter votre programme !
- Effectivement... erreur corrigé ! 

`Pourquoi avoir traité ce cas dans la fonction du dessus et pas dans celle là ?`
- Par simple oublie...
